---

timezone: UTC

defaults:
- scope:
    path: admin/index.html
  values:
    sitemap: false
current_year: 2018

use_contact_form: false

plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

feed:
  path: feed.xml
