---
title: Bersemi Florist
description: >-
  Florist Online yang menjual Buket bunga (Flower Bouquet), Box bunga (Flower
  Box) & Buket Pengantin (Bridal Bouquet) dengan harga yang terjangkau. Kami
  memiliki banyak pilihan jenis bunga yang dapat disesuaikan dengan selera anda.

image:
  path: '/images/single-sunflower.jpg'
  height: 100
  width: 100

logo: /images/new-logo3-no-background1.png
url: 'https://bersemi.id'

social:
  name: Bersemi
  links:
    - https://instagram.com/ber.semi

headline: 'Bersemi Florist: Flower Bouquet, Flower Box & Bridal Bouquet'
current_year: 2018
timezone: UTC
collections:
  portofolio:
    title: Portofolio
    path: "_portofolio/"
    output: true
    permalink: /etalase/:title
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: admin/index.html
  values:
    sitemap: false
current_year: 2018
use_contact_form: false
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
feed:
  path: feed.xml
