# ----
# Site

# social_media:
facebook_url: 'https://facebook.com'
twitter_url: 'https://twitter.com'
instagram_url: 'https://instagram.com'
use_contact_form: false

defaults:
  - scope:
      path: "admin/index.html"
    values:
      sitemap: false

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

feed:
  path: feed.xml
