title: Bersemi Flower Boutique
brand_name: Bersemi
description: >-
  Florist Online yang menjual Buket bunga (Flower Bouquet), Box bunga (Flower
  Box) & Buket Pengantin (Bridal Bouquet) dengan harga yang terjangkau. Kami
  memiliki banyak pilihan jenis bunga yang dapat disesuaikan dengan selera anda.
headline: 'Flower Bouquet, Flower Box & Bridal Bouquet'
email: dikala.bersemi@gmail.com
phone_number: +62 801 212 600
location: |-
  Cilandak, Jakarta
  Indonesia
styling:
  favicon: /images/logo-300x350.png
  logo: /images/logo-300x350.png
social_media:
  facebook_url: ''
  instagram_url: instagram.com/ber.semi
