title: Bersemi Flower Boutique
brand_name: Bersemi
description: 'Flower Bouquet, Flower Box & Bridal Bouquet'
headline: 'Flower Bouquet, Flower Box & Bridal Bouquet'
email: dikala.bersemi@gmail.com
phone_number: +62 801 212 600
location: |-
  Cilandak, Jakarta
  Indonesia
styling:
  favicon: ''
  logo: /images/logo-300x350.png
social_media:
  facebook_url: ''
  instagram_url: instagram.com/ber.semi
