---
# Site

title: "Panduan olshop Kapiten"
brand_name: "Panduan olshop Kapiten"
description: "Kumpulan panduan dan tips untuk membangun bisnis jual-beli online"
headline: "Hello  I'm <strong>Brenda Vargas.</strong> I'm working as the graphic designer of <a href='http://aristotheme.com' target='_blank'>Aristotheme</a> in Mugla doing all sorts of brand stuff."

# Images
# cover: /assets/images/blog-cover.jpg
logo: /assets/img/urku-ico.svg
favicon: /assets/img/urku-ico.svg

# Contact
address: "123 Everystreet Crescent<br>Somewheresville, CA<br>12345 USA</p>"
phone_number: '(301) 123-4567'
email: 'infocompany@contact.com'

# social_media:
facebook_url: 'https://facebook.com'
twitter_url: 'https://twitter.com'
instagram_url: 'https://instagram.com'
use_contact_form: false