backend:
  name: git-gateway
  branch: master

media_folder: "images"
display_url: https://jovial-sammet-8a01e8.netlify.com/

collections:
  - name: "settings"
    label: "Pengaturan"
    create: false # Prevent users from adding documents in this collection
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "primary"
        label: "Utama"
        file: "_data/settings.yml"
        description: "Kamu dapat mengubah isi dan tampilan situsmu dengan mengisi kolom-kolom di bawah ini"
        fields:
          - {label: "Judul Website", name: "title", widget: "string"}
          - {label: "Nama Toko", name: "brand_name", widget: "string"}
          - {label: "Deskripsi Toko", name: "description", widget: "text"}
          - {label: "Kalimat Pembuka", name: "headline", widget: "text"}
          - {label: "Alamat Email", name: "email", widget: string}
          - {label: "Nomor Telepon", name: "phone_number", widget: string}
          - {label: "Alamat Toko (opsional)", name: "location", widget: text, required: false}
          - name: styling
            label: "Tampilan"
            widget: "object"
            fields:
              - {label: "Icon Browser (opsional)", name: "favicon", widget: image, class: "thumb", required: false}
              - {label: "Logo Toko (opsional)", name: logo, widget: image, required: false}
              # - {label: "Warna Utama", name: primary_color, widget: string, required: false}
              # - {label: "Warna Sekunder", name: secondary_color, widget: string, required: false}
          - name: social_media
            label: "Profil Media Sosial"
            widget: "object"
            fields:
              - {label: "Facebook", name: facebook_url, widget: string, required: false}
              - {label: "Twitter", name: twitter_url, widget: string, required: false}
              - {label: "Instagram", name: instagram_url, widget: string, required: false}

      - name: "portofolio"
        label: "Etalase"
        file: "_data/portofolio.yml"
        create: true
        delete: true
        editor:
          preview: false
        fields:
          - {label: "Judul", name: "title", widget: "string"}
          - {label: "Foto", name: "display_picture", widget: "image"}
          - {label: "Deskripsi", name: "description", widget: "markdown"}
          - {label: "Kategori", name: "category", widget: "string", required: false}
